### ISSUE TITLE
Add SWT 4.5

### ISSUE THREAD

**Issue by hennr** [maven-eclipse/swt-repo#1]
Yep, we should do that.

**Comment by TheLQ** [comment]
I see you were one of the maintainers on the old swt-repo on Google code. 

Over the past week I've actually been trying to setup my own repo at https://github.com/swt-maven/swt-maven.github.io . I ended up writing my own scrape script to get all the 4.5 milestone releases from the directory index of one of the mirrors as swt-release-fetcher was kinda complicated and only worked with the latest release

I'd like to help to get this repo setup so there isn't multiple repos. Less duplication + more maintainers = a stable, reliable repository. Do you need any help?

**Comment by hennr** [comment]
Nice one, I've invited you.

**Comment by TheLQ** [comment]
Thanks, glad I can help!

I guess first is how do you want to organize this. Github doesn't really provide an easy web view of the repo like google code does (no randomrepo.googlecode.com equivalent), it only works with repos named username.github.io or a branch named gh-pages

Do you want me to fork my repo here and rename it to maven-eclipse.github.io? Then I can work in importing past releases.

**Comment by hennr** [comment]
Well, I don't have a need to browse the repo in a different way than the view you get when landing at https://github.com/maven-eclipse/swt-repo?files=1

Can you simple pull in you scraper script and add the missing artefacts to the structure provided here?

Am 27. Mai 2015 23:30:24 MESZ, schrieb Leon Blakey notifications@github.com:

> Thanks, glad I can help!
> 
> I guess first is how do you want to organize this. Github doesn't
> really provide an easy web view of the repo like google code does (no
> randomrepo.googlecode.com equivalent), it only works with repos named
> username.github.io or a branch named gh-pages
> 
> Do you want me to fork my repo here and rename it to
> maven-eclipse.github.io? Then I can work in importing past releases. 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/maven-eclipse/swt-repo/issues/1#issuecomment-106085228

## 

Von unterwegs, deshalb etwas kürzer.

**Comment by hennr** [comment]
@TheLQ  Any opinion on pulling the script into the swt-repo project and importing the newer releases?

**Comment by TheLQ** [comment]
IMO https://maven-eclipse.github.io/ looks a lot cleaner than https://raw.githubusercontent.com/maven-eclipse/swt-repo/master . You also can do HTML redirects so when a user goes to that URL it will redirect them to the main repo or a readme instead of "400: Invalid request". Eg I've done this with both http://swt-maven.github.io or http://swt-maven.github.io/maven so even if your copying it from the POM you get pointed to some information

I'd like to add the other jars to the script, but where do I download them? Where did the below jars come from? Are all 7 jars necessary to run JFace (keeping in mind that SWT alone takes ~300 MB)?
-  core/org.eclipse.core.commands
- draw2d/org.eclipse.draw2d
- equinox/org.eclipse.equinox.common
- gef/org.eclipse.gef
- jface/org.eclipse.jface
- osgi/org.eclipse.osgi
- ui/org.eclipse.ui.workbench

**Comment by hennr** [comment]
Well, to your first point:
I would like to avoid a restructuring / change of the urls that the swt repo at google code and a stackoverflow issue point to. I'm fine with adding redirects though. Are you ok with that?

Regarding the jface jars:
They were added by Uri, so I don't know exactly. I guess they have been downloaded from http://www.eclipse.org/swt/

Do you actually use jface? I never did, so I would be fine with deleting these jars.

If you would like to maintain them anyway, I would suggest creating a second project (maven-eclipse/jface-repo) to avoid hitting a github repo limit.

**Comment by ppawel** [comment]
How's it going with 4.5? Are you waiting for the final release or will you put RC in the repo?

**Comment by hennr** [comment]
@TheLQ Any answers so far?
I'm good with this project to be a do-ocracy and thus taking the approach that is being worked on mostly, but we should make a decision now.

**Comment by TheLQ** [comment]
Sorry i've done the work, just forgot to update the issue. There are two repos: dev-releases and maven-eclipse.github.io. Each has a common core branch that contains the script and other files, master contains all of the distributed jars and is merged with core when needed. Each README has more info.

I've got each repo down to around 150mb. The main repo will last a long time, dev-releases might need to be rebuilt eventually to stay under 1gb. I'll put 4.5 in the main repo when its released.

All of this work is pushed here already and should work.

At work we use swtbot so I've been looking on how to import it. There is a jface jar in the eclipse sdk which isnt to hard to get. The "swtbot finder" however is in a eclipse p2(?) repo, and will need a customized pom for dependencies like log4j. Its a work in progress.

Also looking into how to get some of the 3.x swt jars into the script. I'm a little busy at the moment but I'll work on it when i can

**Comment by TheLQ** [comment]
4.5 has been added to maven-eclipse.github.io

**Comment by TheLQ** [comment]
Updated README pointing users to new repo

**Comment by hennr** [comment]
@TheLQ Thanks!
